### ISSUE TITLE
plot 함수 에러

### ISSUE THREAD

**Issue by YoungjunNa** [lovetoken/rdevteam#20]
다음과 같은 에러가 발생합니다.

<img width="437" alt="2018-10-24 9 24 55" src="https://user-images.githubusercontent.com/28377612/47398359-bce07080-d76e-11e8-8083-dfc44343e029.png">

**Comment by lovetoken** [comment]
안녕하세요 영준님 이슈언급 고마워요!
`JS()` 함수의 namespace 명시로 본 에러를 해결하였고 V0.2.4 커밋하였습니다.
