### ISSUE TITLE
naverRank() 에서 "title" css selector 가 동작하지 않는 문제

### ISSUE THREAD

**Issue by lovetoken** [lovetoken/rdevteam#21]
보안정책상의 문제인지 "title" css selector 가 동작하지않는듯 보임. 
결론적으로 Top 20 개 값이 모두 NA 를 반환하고 있음.

**Comment by YoungjunNa** [comment]
ㅎㅎ 저도 해보려니 안되더군요~

**Comment by YoungjunNa** [comment]
<img width="549" alt="2018-11-23 9 56 30" src="https://user-images.githubusercontent.com/28377612/48925353-25557580-ef06-11e8-91fa-c5663c25d47a.png">

매크로를 돌린것도 아닌데 두세번? 시도했는데 네이버에서 막네요..

**Comment by lovetoken** [comment]
영준님 위에 stopit 사이트는 이 이슈와 어떤 관련이 있는건가요??

**Comment by YoungjunNa** [comment]
naverRank 함수 안에 url 링크가 다음과 같은데
https://datalab.naver.com/keyword/realtimeList.naver

naverRank 함수를 몇번 돌린다음에
요 싸이트로 직접 접속을 시도하면 ip를 차단하더라구요.. 그때 나오는게 바로 위 화면이에요~ ㅎㅎ 네이버에서 그만해.. 라고 말하는듯..

**Comment by lovetoken** [comment]
와 그럴때 stopit 사이트로 우회접속이 되는개념인가보군요.
'Stop it!'  이란 문장을 저렇게 외치다니.. 네이버답네요ㅋㅋ
