### ISSUE TITLE
2차 연관 검색어 plot 반환 오류 & 패키지 의존성 오류

### ISSUE THREAD

**Issue by YoungjunNa** [lovetoken/rdevteam#22]
<a href="https://asciinema.org/a/9zsnGKM5vCamR9Sq0gAnPYFJo" target="_blank"><img src="https://asciinema.org/a/9zsnGKM5vCamR9Sq0gAnPYFJo.svg" /></a>

**Comment by lovetoken** [comment]
엇 영준님 asciinema 잘 보았습니다 ㅎㅎ
저도 저 에러가 그대로 재현이 되네요... 확인해 보겠습니다

**Comment by lovetoken** [comment]
확인해보니 2차연관검색어 즉 `depth = 2` 조건일 때 반환되는 결과객체가 `nr` class 가 덧붙여지지 않았던 문제가 있었습니다. 
이로인해 `plot()` 제너릭 함수에 입력하여 실행하면 `plot.nr()` 로 실행되지 않았었던거였구요.
이 문제를 해결하여 Commit 완료 하였습니다.

0f9c9afa93f3b3469bf63d0b4f502b016d7ae212

**Comment by lovetoken** [comment]
아 그러고보니 이 이슈는 plotting 의 이슈만이 아니었군요.
패키지 의존성 문제는 아직 미해결인데요. (closed > reopen)
윈도우 OS 환경에서는 의존성 에러가 나타나지 않는걸 확인했습니다.
리눅스 OS 환경에서도 한번 확인해 본 후 개선이 필요하면 하도록 하겠습니다.
