### ISSUE TITLE
함수 로딩 중 에러 메시지

### ISSUE THREAD

**Issue by YoungjunNa** [lovetoken/rdevteam#5]
다음과 같이 에러가 나오는데 감을 못잡겠네요 ㅎㅎ
![image](https://user-images.githubusercontent.com/28377612/35323969-accc3822-0132-11e8-81e2-4be6fbb3fc60.png)

**Comment by lovetoken** [comment]
어떠한 상황에서 스샷과 같은 오류가 일어나던가요!?

**Comment by YoungjunNa** [comment]
패키지 로딩 후 naverRelation 함수를 적는.. 과정가운데 자동완성과 함께 에러가 뜨더라구요 ㅎㅎ

내일 시간되면 영상으로 찍어서 공유할게요!

**Comment by lovetoken** [comment]
그렇군요
윈도우 환경에서 테스트를 해보지 못했는데 한번 확인해 보겠습니다.

**Comment by YoungjunNa** [comment]
https://youtu.be/4mnAFP5Z0d8

**Comment by lovetoken** [comment]
V0.1.4 Commit 을 통해 본 버그를 해결하였습니다. 

7993c02c85c2c599ffbb5091b368144c1afd31b1

**Comment by YoungjunNa** [comment]
감사합니다 잘 되네요~! 무엇이 문제였을까요?

**Comment by lovetoken** [comment]
전 버전은 도움말(document)을 한글로 작성했는데 
모두 영어로 바꾸니 위 문제가 나지 않더군요 🤔
