### ISSUE TITLE
매킨토시에서 nvrGraph 함수 실행시 encoding 문제(?)

### ISSUE THREAD

**Issue by YoungjunNa** [lovetoken/rdevteam#6]
매킨토시 환경에서 nvrGraph 함수를 돌려봤는데요.
글씨가 잘 안나오네요 제 Mac 설정 문제일까요?

![image](https://user-images.githubusercontent.com/28377612/35379201-abe6ccee-01f8-11e8-9114-990b969f8189.png)

**Comment by lovetoken** [comment]
제 맥에서도 동일한 문제가 발생합니다.
매킨토시 이용시 한글표현의 고질적인 문제기도 한데요.

```
par(family = "AppleGothic")
```

으로 초기설정 하고도 똑같은 문제가 발생해서 
igraph 패키지 단에서의 설정이 더 필요한지 좀 더 알아보고 있는 중입니다.

**Comment by lovetoken** [comment]
V0.2.0(7c4a25796a61cf89a2b48c6a7174c2c9243c767d) 에서 `plot.nr()` 함수로 통합되면서 `nvrGraph()` 함수가 삭제되었습니다. 따라서 본 이슈를 닫습니다.
