### ISSUE TITLE
networkPlot 및 networkplot_3d 함수 개선의견

### ISSUE THREAD

**Issue by YoungjunNa** [lovetoken/rdevteam#9]
기섭님 함수가 잘 작동되네요 신기방기- ㅎㅎ 개선의견 몇개 내봅니다.

1. networkPlot: 
화살표가 글씨를 가리는 경우가 생기는 것 같아요~ 화살표 없이 봐도 좋을 듯 합니다.

2. networkPlot 및 networkplot_3d
위 두 함수 작성 시 naverRelation2 결과를 쓰는데요 networkPlot(naverRelation2("문재인") <- 요런 식으로요.. naverRelation2함수를 아에 내장(?) 시키면 좀 편하지 않을까 싶네요~ 어짜피 2차 연관검색어 데이터로 시각화 시키는 것이니까요~

**Comment by lovetoken** [comment]
1, 2번 내용에 대부분을 공감합니다.

1번은 화살표만 없애는 방법을 찾게된다면 누구나 공유주시구요~ (어떤인자가 화살표인자인지 못찾겠어요 ㅎㅎ)

2번의 경우 제 생각은 
2차연관검색 결과물이 데이터(data.frame) 및 시각화 2개가 모두 반환될 수 있어야 좋아보입니다.
시각화 결과 외에 내부데이터를 응용시키고 싶은 니즈도 있을것 같아서요.

**Comment by YoungjunNa** [comment]
2차 연관검색어 결과물 관련 효진님 생각에 동의해요~
naverRelation2 함수 안에 시각화를 TRUE/FALSE 옵션으로 넣는.. 그런거 말씀하시는거 맞나요? ㅎㅎ

**Comment by lovetoken** [comment]
`networkPlot()`, `networkplot_3d()` 함수는 함수명칭대로 시각화결과물을 기본적으로 출력하되 return 값을 2차연관검색어 결과에 해당되는 데이터프레임으로 주는 옵션인자 `out.result` 를 생각해 보았습니다.

**Comment by Gi-Seop** [comment]
저도 통합하는 것을 생각해보았는데, 모듈화 하는 것이 좋다고 생각해서 나눈상태로 작업했습니다.
효진님 말처럼 커스터마이징이 가능한 자료셋트가 반환되는 것이 응용하기 더 좋기 때문입니다.
시각화 함수 관점에서도 아까 말씀하신 부분처럼 사용자 개개인이 필요에 따라 조절할 수 있는 부분이 필요할듯 합니다. 
이 부분은 의견이 조금 갈리는것 같네요. 더 논의해보면 좋겠습니다.

**Comment by lovetoken** [comment]
V0.2.0 (7c4a25796a61cf89a2b48c6a7174c2c9243c767d)를 통해 통합하였습니다.
